services:
  auth-db:
    container_name: auth-api-database
    image: postgres:15
    environment:
      - POSTGRES_DB=ecommerce-auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-db:
    container_name: product-api-database
    image: postgres:15
    environment:
      - POSTGRES_DB=ecommerce-product-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq-service
    image: rabbitmq:3.13.7-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    
  email-service:
    container_name: email-service
    build:
      context: ./services/email
      target: development
    env_file:
      - ./services/email/.env
    volumes:
      - ./services/email:/app
      - /app/node_modules
    command: yarn dev:watch
    depends_on:
      rabbitmq:
        condition: service_healthy

        
  auth-service:
    container_name: auth-api
    build: 
      context: ./services/auth
      target: development
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@auth-db:5432/ecommerce-auth-db?schema=public
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./services/auth:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && yarn dev:watch"

  product-service:
    container_name: product-api
    build:
      context: ./services/product
      target: development
    ports:
      - "3002:3002"
    env_file:
      - ./services/product/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@product-db:5432/ecommerce-product-db?schema=public
    depends_on:
      product-db:
        condition: service_healthy
    volumes:
      - ./services/product:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && yarn dev:watch"
    

volumes:
  rabbitmq-data:
  rabbitmq-log:
  auth-data:
  product-data: