services:
  auth-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=ecommerce-auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data

  product-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=ecommerce-product-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5433"
    volumes:
      - product-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - NODE_ENV=development
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    
  auth-service:
    build: ./services/auth
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecommerce-product-db
    depends_on:
      - auth-db

  product-service:
    build: ./services/product
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ecommerce-product-db
    depends_on:
      - product-db
    

volumes:
  rabbitmq-data:
  rabbitmq-log:
  auth-data:
  product-data:
  