version: '3.8'

services:
  auth-service:
    build: ./services/auth
    ports:
      - "3001:3001"
    environment:
      - DB_URL=postgres://postgres:postgres@auth-db/auth
    depends_on:
      - auth-db

  auth-db:
    image: postgres
    env_file:
      - ./services/auth/.env
    volumes:
      - auth-data:/var/lib/postgresql/data